### ISSUE TITLE
使用AgentMainDemo加载AgentMain.jar时报错

### ISSUE THREAD

**Issue by SSS607** [KpLi0rn/AgentMemShell#2]
大佬，如题目所示，报错内容如下：

`javaAgent_memshell.AgentMain.AgentMainDemo
id is 412
java.lang.NoClassDefFoundError: AgentMain (wrong name: javaAgent_memshell/AgentMain/AgentMain)
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:304)
	at sun.instrument.InstrumentationImpl.loadClassAndCallAgentmain(InstrumentationImpl.java:411)
Exception in thread "main" com.sun.tools.attach.AgentInitializationException: Agent JAR loaded but agent failed to initialize
	at sun.tools.attach.HotSpotVirtualMachine.loadAgent(HotSpotVirtualMachine.java:121)
	at com.sun.tools.attach.VirtualMachine.loadAgent(VirtualMachine.java:540)
	at javaAgent_memshell.AgentMain.AgentMainDemo.main(AgentMainDemo.java:19)
Agent failed to start!
Exception in thread "Attach Listener" 
Process finished with exit code 1
`
百思不得其解啊。。。

**Comment by SSS607** [comment]
已解决
